### ISSUE TITLE
RESTDataSource serializes undefined values as "undefined"

### ISSUE THREAD

**Issue by borekb** [apollographql/datasource-rest#24]
I have a data source like this:

```js
class MyApi extends RESTDataSource {
  constructor() {
    super();
    this.baseURL = 'https://my-api.example.com/';
  }

  async getUser(query) {
    return this.get('/user', query);
  }
}
```

This is my resolver:

```js
const userResolver = (_, __, {dataSource: {myApi}}) => {
  const query = {
    userId: "1",
    optionalParam: undefined,
  };
  return myApi.getUser(query);
}
```

This leads to this HTTP request:

```
GET /myApi/user?userId=1&optionalParam=undefined
```

while I think it would be more logical if this was fetched:

```
GET /myApi/user?userId=1
```

I think these lines implement the behavior:

https://github.com/apollographql/apollo-server/blob/d3882350fb768bde2d599343c257dc71400cb360/packages/apollo-datasource-rest/src/RESTDataSource.ts#L226-L229

**Comment by glasser** [comment]
I do understand the desire here, and I see a bunch of 👍 across this and the duplicate issue #26 over the years. The treatment of objects with keys with `undefined` values in JS is a bit inconsistent: it's not identical to leaving out the key, but some important APIs like `JSON.stringify` treat it that way. I can definitely understand the desire to write

```ts
return this.get('path', {
  params: {
    foo,  // which might be null/undefined
    bar: computeBar(), // similar
  },
});
```

and have it just work.

That said, our implementation of URL query parameters is based on the DOM `URL` API's [`URLSearchParams` class](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams), and we allow you to pass any representation of search parameters supported by that class's constructor.  In addition to an object, you can pass a string that's already serialized, or an array of two-element arrays of strings, or in fact any iterable object that lets you iterate and produce two-element arrays of strings.  And this API (which is about as "standardized" as you can get for an URL-producing API) assumes you give it strings and converts anything that isn't a string to a string, including `undefined` to `"undefined"`.

I don't think it's reasonable for our project to effectively reimplement the entirety of the `URLSearchParams` API (supporting all the different ways params can be specified) just to strip out `undefined` first.  And I think only stripping in the "object" case and not the others would be inconsistent.

Also there's an interesting question as to whether we should strip `null` too. Doing that would not be consistent with `JSON.stringify`! But it probably makes sense.

Also note that the TypeScript types are correct: at least in the current version, `this.get('foo', { params: { foo: undefined } })` fails to typecheck. So if you're using TS this at least shouldn't surprise you at runtime. (I'm assuming here and hereafter that you use strictNullChecks if you use TS.)

I can think of two approaches to take here. (Note that I consider them both to be backwards-incompatible but we will probably be releasing `@apollo/datasource-rest@5.0.0` with a variety of improvements soon.)

(a1) The first is to give up on the idea of supporting any legal `URLSearchParams` constructor argument here, and *just* allow you to pass an object. So `params` would now have type `Record<string, unknown>` and we'd explicitly strip `undefined` (and null?) before passing it to `new URLSearchParams`. Anyone who may have been taking advantage of the other types allowed for `params` would have to adapt their code.

(a2) As a slight middle ground, we could declare `params: Record<string, unknown> | URLSearchParams`, so anybody using the other types can just manually write `params: new URLSearchParams('x=y&z=w')`.

(b) The second is to declare the current state of the world to be intentional (after all, it matches the most standardized relevant API) and document how to achieve the goals shown by the snippet above. There are at least three pretty easy workarounds, and note that these workarounds also let you choose for yourself how `null` is handled, etc.

(b1) Just use lodash:

```js
import { omitBy, isUndefined } from 'lodash';
return this.get('path', {
  params: omitBy({
    foo,
    bar: computeBar(),
  }, isUndefined),  // or you can use isNil to include null too
});
```

This is pretty easy. One downside is the TS types aren't smart enough to know the overall effect of omitBy+isUndefined so this probably doesn't work with TS.

(b2) Write your own TS function like

```ts
function omitUndefinedValues(x: Record<string, unknown>): Record<string, NonNullable<unknown>> {
  const y: Record<string, NonNullable<unknown>> = {};
  for (const [key, val] of Object.entries(x)) {
    if (val !== undefined && val !== null) {
      y[key] = val;
    }
  }
  return y;
}
```

Is there something like this on npm somewhere? We could publish it from the `apollo-utils` repository if that helps... This solves the TS issue of (b1).

(b3) Actually take advantage of the flexibility of the URLSearchParams constructor:

```ts
const bar = computeBar(),
return this.get('path', {
  params: [
    ...(foo !== undefined ? [['foo', foo]] : []),
    ...(bar !== undefined ? [['bar', bar] : []),
  ],
});
```

This requires no dependencies and typechecks properly out of the box, but is a bit more verbose (especially for the "computed directly in the call" use case).  And of course, anyone who has already discovered this workaround (or otherwise likes this pattern) would be broken if we chose (a).





I am leaning towards saying hey, who are we to say we know more than the designers of the DOM URL API, let's go with (b) and document how to do (b2) [with our own package] or (b3).  But maybe we should go with (a2) instead.

**Comment by borekb** [comment]
@glasser I don't have the mental capacity right now to carefully consider all the options but thank you so much for such a detailed / thoughtful response!

**Comment by glasser** [comment]
After sleeping on it, I'm feeling reasonably good about a major-version bump for (a2).
