### ISSUE TITLE
add HEAD requests in RESTDataSource Class

### ISSUE THREAD

**Issue by devdudeio** [apollographql/datasource-rest#27]
Some endpoints of my REST API can be requested via a HEAD request but head is not implemented yet.

```
export class MyFancyAPI extends RESTDataSource {
    async countFancyDataset() {
        const response = await this.head(`countFancyDataset`); // myFancyDataset: 413212  (in Response Header and body will be empty)
        ...
    }
}
```

**Comment by trevor-scheer** [comment]
Ok, having familiarized myself with `HEAD` semantics I feel prepared to discuss this and propose a couple options.

* `HEAD` bodies in responses must be ignored, meaning all of their useful data exists in the response headers. They ought to be treated as a `GET` request with no response body.
* `RESTDataSource` in its current form doesn't expose the `response` object (just the parsed `body`) in its return value of `fetch` or the helper "http method" methods.

Based on this information, I'm going to assume people want access to the response headers when the make a `HEAD` request (else it's just an empty string). AFAICT, @Phoenix1405's PR mentioned above did not address this. I'm really not sure how useful this API addition can be otherwise, though. 

I propose 2 possible options (with the option of 1, then later 2):
1) Add a `head` method which breaks convention from the other convenience methods, i.e. it does not return a parsed `body` and instead returns either the whole `response` object or just its `headers`. This will result in some additional internal complexity around `HEAD` being special (i.e. the `fetch` method will have 2 different return types and have to look for `HEAD`, etc.). It also creates an inconsistency in the API (making it unique among the other convenience methods).
2) In a breaking change to the API, start returning additional data in the convenience methods (either the whole `response` object alongside a parsed `body` or something similar, but at a bare minimum the `headers` as well).

I'd be interested in hearing input on these options from anyone on this thread. I'm leaning towards 2 myself since it offers a more robust and consistent API.
