### ISSUE TITLE
Error solving URL dynamically RestDataSource

### ISSUE THREAD

**Issue by PauloMarceloNogueira** [apollographql/datasource-rest#37]
Version
APOLLO RESTDATASOUCE = apollo-datasource-rest": "^0.9.3",
APOLLO SERVER = "apollo-server-lambda": "^2.16.1",
TYPESCRIPT = ""typescript": "^4.0.2""

I trying follow the documentation steps to set a dynamic url based on my ENV (setted in context)
But its show warning message `'baseURL' is defined as a property in class 'RESTDataSource<Context>', but is overridden here in 'TransactionsAPI' as an accessor.`

Snippet: 
```javascript
export default class TransactionsAPI extends RESTDataSource<Context> {
  constructor() {
    super();
  }

  get baseURL() {
    if (this.context.env === "development") {
      return "https://dev.api_example.com.br";
    } else if (this.context.env === "production") {
      return "https://prod.api_example.com.br";
    }
  }
  async myFunction() {
   return this.post(`/patch`)
  }
}
```

Im following this steps
http://apollographql.com/docs/apollo-server/data/data-sources/#resolving-urls-dynamically

Thank you!

**Comment by glasser** [comment]
When this issue was opened, our docs suggested either overriding `get baseURL()` or `resolveURL()`, but we removed the previous suggestion last year in https://github.com/apollographql/apollo-server/pull/5165 for the TS reasons above.

We hope overriding resolveURL solves the problems above; if `resolveURL` isn't sufficient, please file a new issue.

(baseURL is only used by the superclass resolveURL method. If you do need a dynamic base URL that is not constant for a single RESTDataSource, one option is to just not call `super.resolveURL` in your overridden `resolveURL` at all. We could document that fact about baseURL perhaps?)
