### ISSUE TITLE
[apollo-datasource-rest] Content-type: application/json not added when body is string

### ISSUE THREAD

**Issue by rjoaopereira** [apollographql/datasource-rest#38]
### package
apollo-datasource-rest: 0.9.3

### Expected behaviour
The content-type header, if not present, is added when a [valid](https://stackoverflow.com/questions/7487869/is-this-simple-string-considered-valid-json) JSON is provided in the body.

### Actual behaviour
The content-type header, if not present, is added only if the body contains an object, array or date.

[affected code](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-datasource-rest/src/RESTDataSource.ts#L232)

A simple [example](https://github.com/rjoaopereira/rest-data-source-content-type-json) (please pay no attention to the validity of the queries)

The point is to debug the provided affected code when the query 
`
query{
    hello
    bye
 }
`
is executed.

The hello _query_ passes a string in the body and the _bye_ one passes an object. They both use the datasource's put.

First request:
![imagem](https://user-images.githubusercontent.com/6602887/90246271-27730c80-de2c-11ea-8571-fef1677cfdf2.png)

Second Request:
![imagem](https://user-images.githubusercontent.com/6602887/90246317-4d001600-de2c-11ea-9894-198b38df1a94.png)

**Comment by trevor-scheer** [comment]
Hey @rjoaopereira, sorry for the delay in responding to this.

Can you help me understand what you're trying to do that this behavior is breaking?
* Do you want to set a body as a plain text (double-quote escaped?) string and have us still set the `application/json` header since it's valid JSON?
* Are you trying to pass in already stringified JSON as the body and have us recognize that and set the header?

For 1: I'm not sure I see the value, but if this is your use case I'm interested to hear about it. Why is it useful to set that header?
For 2: I think this adds a fair amount of overhead to look at every string body, try and parse it, then assign the header if it succeeds (unless there's a better, faster way to detect valid JSON). Would parsing the object in the resolver or in the `fails()` function be reasonable?

This can be worked around right now (in the v3 version) by using the `willSendRequest` hook to inspect the body and set the header yourself if you choose to do that. Unfortunately this can't be done in v4 yet due to a [separate issue](https://github.com/apollographql/datasource-rest/issues/83) (which I have a PR open for).

**Comment by trevor-scheer** [comment]
We think this is working as intended. Happy to discuss further.
