### ISSUE TITLE
Can't read set-cookie headers from backend server properly

### ISSUE THREAD

**Issue by AfzalH** [apollographql/datasource-rest#75]
I'm using apollo server as an orchestration layer which connects and gets data from other backend servers.
I need to forward the set-cookie headers from backend server. Works well if there's one set-cookie header but if there are multiple there's a problem.
```javascript
const { RESTDataSource } = require("apollo-datasource-rest");

class MyDataSource extends RESTDataSource {
  constructor() {
    super();
    this.baseURL = 'https://example.com';
  }

  didReceiveResponse(response, _request) {
    // here response.header is an Iterable and get method gives a string joining multiple header
    let cookies = response.headers.get("set-cookie");
    console.log(cookies);
    return super.didReceiveResponse(response, _request);
  }

  async resolverFunc(body) {
    // ...
  }
}
```
return type for `response.headers.get` is string | null but in this case it should be array.
if we console log `response.headers` we see that inside Symbol map the set-cookie header is actually an array but gets converted to string when trying to get the value using the get method.
Couldn't find a way to get the original array.

**Comment by glasser** [comment]
This is unfortunately not particularly fixable in a compelling way: we've chosen to orient this package around the Fetch API but the Fetch API does not let you differentiate between "a header showed up twice" and "the same thing but joined with comma-space".  (This API was designed for browsers where it explicitly cannot see Set-Cookie headers!) Making RESTDataSource work with multiple Fetch implementations is a pretty key part of the design so we can't really rely on response.headers.raw() in our general implementation.

If you're sure you're using node-fetch then you can do what @cjonesdoordash showed and use `response.headers.raw()`. However, if the operation ends up interacting with HTTPCache then the response will get cloned and that will fail.  If it's not a GET (and you don't explicitly set `ttl` via `cacheOptions` or `cacheOptionsFor`) then that clone won't happen, so the @cjonesdoordash method will work fine. I suspect many Set-Cookie responses are to POSTs anyway so that should be OK?

What I'd like to do is add a test that if  you send a POST (with the default `node-fetch` fetcher) that gets multiple set-cookie headers, you can use the `raw()` trick on the response. For various reasons we should finish #110 first.
